import React from 'react';
import { Web3 } from 'web3';

// Providers
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Web3Provider } from './providers/web3/web3-provider';

// Components
import { Header } from './components/header/header';
import { Footer } from './components/footer/footer';

import './globals.css';

// RPC endpoint
const web3 = new Web3(`https://eth-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`);

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode,
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Web3Provider>
                    <div className="h-screen flex flex-col justify-between">
                        <Header />

                        <div className="h-full">
                            {children}
                        </div>

                        <Footer />
                    </div>
                </Web3Provider>
            </body>
        </html>
    );
}
